<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="ChatApp.Chat" %>


<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>SignalR Chat : Chat Page</title>

    <link href="Content/bootstrap.css" rel="stylesheet" />
    <link href="Content/style.css" rel="stylesheet" />
    <link href="Content/font-awesome.css" rel="stylesheet" />

    <script src="Scripts/jQuery-3.5.1.min.js"></script>
    <script src="Scripts/jquery.signalR-2.4.1.min.js"></script>
    <script src="Scripts/date.format.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs">
    </script>

    <script type="text/javascript">

        $(function () {

            // Declare a proxy to reference the hub. 
            var chatHub = $.connection.chatHub;
            registerClientMethods(chatHub);
            // Start Hub
            $.connection.hub.start().done(function () {

                registerEvents(chatHub)

            });
            $(document).on('change', '#<%= FileUpload1.ClientID%>', function (e) {

                  var tmppath = URL.createObjectURL(e.target.files[0]);
                  $("#ImgDisp").attr('src', tmppath);

              });
        });

        function registerEvents(chatHub) {

            var name = '<%= this.userName %>';

             if (name.length > 0) {
                 chatHub.server.connect(name);

             }


             $('#btnSendMsg').click(function () {

                 var msg = $("#txtMessage").val();

                 if (msg.length > 0) {

                     var userName = $('#hdUserName').val();

                     var date = GetCurrentDateTime(new Date());

                     chatHub.server.sendMessageToAll(userName, msg, date);
                     $("#txtMessage").val('');
                 }
             });

             $("#txtMessage").keypress(function (e) {
                 if (e.which == 13) {
                     $('#btnSendMsg').click();
                 }
             });
        }

        function registerClientMethods(chatHub) {


            // Calls when user successfully logged in
            chatHub.client.onConnected = function (id, userName, allUsers, messages, times) {

                $('#hdId').val(id);
                $('#hdUserName').val(userName);
                $('#spanUser').html(userName);

                // Add All Users
                for (i = 0; i < allUsers.length; i++) {

                    AddUser(chatHub, allUsers[i].ConnectionId, allUsers[i].UserName, allUsers[i].UserImage, allUsers[i].LoginTime);
                }

                // Add Existing Messages
                for (i = 0; i < messages.length; i++) {
                    AddMessage(messages[i].UserName, messages[i].Message, messages[i].Time, messages[i].UserImage);

                }
            }

            // On New User Connected
            chatHub.client.onNewUserConnected = function (id, name, UserImage, loginDate) {
                AddUser(chatHub, id, name, UserImage, loginDate);
            }


            // On User Disconnected
            chatHub.client.onUserDisconnected = function (id, userName) {

                $('#Div' + id).remove();

                var ctrId = 'private_' + id;
                $('#' + ctrId).remove();


                var disc = $('<div class="disconnect">"' + userName + '" logged off.</div>');

                $(disc).hide();
                $('#divusers').prepend(disc);
                $(disc).fadeIn(200).delay(2000).fadeOut(200);

            }

            chatHub.client.messageReceived = function (userName, message, time, userimg) {

                AddMessage(userName, message, time, userimg);
            }


        }

    </script>
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server" ></asp:ScriptManager>
        <div class="content-wrapper">

                   <header class="main-header" style="background:#bedaeb">
        <!-- Logo -->
        <a href="index2.html" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>SignalR</b> Chat App</span>
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
        
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->

              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="<%= userImage %>" class="user-image" alt="User Image" />
                  <span class="hidden-xs"><%= this.userName %></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header" >
                    <img src="<%= userImage %>" class="img-circle" alt="User Image" />
                    <p style="color:#000000;">
                      <%= userName %>
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a  class="btn btn-default btn-flat" data-toggle="modal" href="#ChangePic">Change Picture</a>
                    </div>
                    <div class="pull-right">
                        <asp:Button ID="btnSignOut" runat="server" CssClass="btn btn-default btn-flat" Text="Sign Out" OnClick="btnSignOut_Click" />
                     <%-- <a href="#" class="btn btn-default btn-flat">Sign out</a>--%>
                    </div>
                  </li>
                </ul>
              </li>
              <!-- Control Sidebar Toggle Button -->

            </ul>
          </div>
        </nav>
      </header>

            <div class="row">

                <div class="col-md-8">
                    <!-- DIRECT CHAT PRIMARY -->
                    <div class="box box-primary direct-chat direct-chat-primary">
                       <div class="box-header with-border">
                            <h3 class="box-title" style="color:dimgrey;">Welcome to Discussion Room <span id='spanUser'></span></h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <!-- Conversations are loaded here -->
                                    <div class="box-body" id="chat-box">
                                            <!-- Conversations are loaded here -->

                                            <div id="divChatWindow" class="direct-chat-messages" style="height: 450px;">
                                            </div>

                                            <div class="direct-chat-contacts">
                                                <ul class="contacts-list" id="ContactList">

                                                    <!-- End Contact Item -->
                                                </ul>
                                                <!-- /.contatcts-list -->
                                            </div>
                                            <!-- /.direct-chat-pane -->
                                     
                                            </div>

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">

                            <textarea id="txtMessage" class="form-control" ></textarea>

                            <div class="input-group" style="float: right;">
                                <input class="form-control" style="visibility: hidden;" />
                                <span class="input-group-btn">
                                    <input type="button" class="btn btn-primary btn-flat" id="btnSendMsg" value="send" />

                                </span>

                            </div>

                        </div>
                        <!-- /.box-footer-->
                    </div>
                    <!--/.direct-chat -->
                </div>
                <!-- /.col -->
                <div class="col-md-4">

                    <div class="box box-solid box-primary">

                        <div class="box-header with-border">
                            <h3 class="box-title">Online Users <span id='UserCount'></span></h3>
                        </div>

                        <div class="box-footer box-comments" id="divusers">
                        </div>

                    </div>
                </div>

                <!-- /.col -->


                <!-- /.col -->

                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>

        <span id="time"></span>
        <input id="hdId" type="hidden" />
        <input id="PWCount" type="hidden" value="info" />
        <input id="hdUserName" type="hidden" />

          <div class="modal fade" id="ChangePic" role="dialog">
        <div class="modal-dialog" style="width: 700px">
            <div class="modal-content">
                <div class="modal-header bg-light-blue-gradient with-border">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Change Profile Picture</h4>
                </div>
                <div class="modal-body">
                    <div class="container">

                        <asp:UpdatePanel ID="UpdatePanel1" runat="server">
                                                   
                        <Triggers>
                            <asp:PostBackTrigger ControlID="btnChangePicModel" />
                        </Triggers>
                        <ContentTemplate>

                        <div class="row">
                            <div class="col-md-12">
                                <table class="table table-bordered table-striped table-hover table-responsive" style="width: 600px">

                                    <tr>

                                        <div class="col-md-12">
                                            <td class="text-primary col-md-4" style="font-weight: bold;">
                                                <img id="ImgDisp" src="" class="user-image" style="height: 100px;" />
                                            </td>
                                            <td class="text-primary col-md-4" style="font-weight: bold;">
                                                <asp:FileUpload ID="FileUpload1" runat="server" class="btn btn-default"/>
                                            </td>
                                            <td class="col-md-4">
                                                
                                              <asp:Button ID="btnChangePicModel" runat="server" Text="Update Picture" CssClass="btn btn-flat btn-success" OnClick="btnChangePicModel_Click" />

                                                   
                                            </td>
                                        </div>

                                    </tr>


                                    <tr>
                                        <div class="col-md-12">

                                            <td class="col-md-12" colspan="3"></td>
                                        </div>

                                    </tr>


                                </table>
                            </div>
                        </div>

                    </div>
                </div>
                 </ContentTemplate>
                  </asp:UpdatePanel>
            </div>
        </div>
    </div>
            </div>
          </div>

         <script src="Scripts/bootstrap.min.js"></script>

    </form>
</body>
</html>

